name       : spyder3
version    : 4.1.5
release    : 11
source     :
    - https://github.com/spyder-ide/spyder/archive/v4.1.5.tar.gz : 98f24bd782e2c5d2fcd1033b433692e85dada9f095f86547ba66728e5a26a65f
homepage   : https://www.spyder-ide.org/
license    :
    - BSD-3-Clause
    - CC-BY-2.5
    - CC-BY-3.0
    - CC-BY-SA-4.0
    - EPL-1.0
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
    - MIT
    - Python-2.0
    - Zlib
component  : programming.ide
summary    : Spyder - The Scientific PYthon Development EnviRonment (Python 3 Version).
description: |
    Spyder is a powerful scientific environment written in Python, for Python, and designed by and for scientists, engineers and data analysts. It offers a unique combination of the advanced editing, analysis, debugging, and profiling functionality of a comprehensive development tool with the data exploration, interactive execution, deep inspection, and beautiful visualization capabilities of a scientific package.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - cython
    - matplotlib
    - pycodestyle
    - pyflakes
    - pylint
    - python-atomicwrites
    - python-chardet
    - python-diff-match-patch
    - python-intervaltree
    - python-keyring
    - python-language-server
    - python-nbconvert
    - python-numpydoc
    - python-opengl
    - python-pandas
    - python-psutil
    - python-qdarkstyle
    - python-qtawesome
    - python-qtconsole
    - python-rope
    - python-spyder-kernels
    - python-watchdog
    - pyxdg
    - scipy
    - sympy
setup      : |
    # Use our python3-jedi version
    sed -i "s|JEDI_REQVER = '=0.17.1'|JEDI_REQVER = '>=0.17.1'|" -i spyder/dependencies.py
build      : |
    %python3_setup
install    : |
    %python3_install

    # Remove windows stuff
    rm $installdir/usr/bin/spyder_win_post_install.py

    # Move icon to pixmaps
    install -dm00644 $installdir/usr/share/pixmaps
    mv $installdir/usr/share/icons/spyder3.png $installdir/usr/share/pixmaps/spyder3.png

    # Remove empty directory
    rm -rf $installdir/usr/share/icons
