name       : spyder3
version    : 3.2.4
release    : 1
source     :
    - https://github.com/spyder-ide/spyder/archive/v3.2.4.tar.gz : 5206a69193038fb29b6d0a5a68591c4222d2abdb058bdfef87081f0d48ea80be
license    : 
    - BSD-3-Clause
    - CC-BY-2.5
    - CC-BY-3.0
    - CC-BY-SA-4.0
    - EPL-1.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
    - MIT
    - Python-2.0
    - Zlib
component  : programming.ide
summary    : Spyder - The Scientific PYthon Development EnviRonment (Python 3 Version).
description: |
    Spyder - The Scientific PYthon Development EnviRonment (Python 3 Version).
builddeps  :
    - pkgconfig(python-3.5)
rundeps    :
    - cython
    - matplotlib
    - numpy
    - pycodestyle
    - pyflakes
    - pygments
    - pylint
    - python3-jedi
    - python3-qt5
    - python-chardet
    - python-nbconvert
    - python-numpydoc
    - python-pandas
    - python-pickleshare
    - python-psutil
    - python-pyzmq
    - python-qtawesome
    - python-qtconsole
    - python-qtpy
    - python-rope
    - python-sphinx
    - scipy
    - sympy
build      : |
    %python3_setup
install    : |
    %python3_install
    rm $installdir/usr/bin/spyder_win_post_install.py
