name       : spyder3
version    : 5.0.2
release    : 15
source     :
    - https://github.com/spyder-ide/spyder/archive/v5.0.2.tar.gz : bf1008a03302b2c48cb0a76b32437ce4cc4f2c38fc8dbff7d70bcc6a1a3820c7
homepage   : https://www.spyder-ide.org/
license    :
    - BSD-3-Clause
    - CC-BY-2.5
    - CC-BY-3.0
    - CC-BY-SA-4.0
    - EPL-1.0
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
    - MIT
    - Python-2.0
    - Zlib
component  : programming.ide
summary    : Spyder - The Scientific PYthon Development EnviRonment (Python 3 Version).
description: |
    Spyder is a powerful scientific environment written in Python, for Python, and designed by and for scientists, engineers and data analysts. It offers a unique combination of the advanced editing, analysis, debugging, and profiling functionality of a comprehensive development tool with the data exploration, interactive execution, deep inspection, and beautiful visualization capabilities of a scientific package.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - cython
    - matplotlib
    - pycodestyle
    - pyflakes
    - pylint
    - python-atomicwrites
    - python-chardet
    - python-cookiecutter
    - python-intervaltree
    - python-keyring
    - python-nbconvert
    - python-numpydoc
    - python-opengl
    - python-pandas
    - python-psutil
    - python-pyls-black
    - python-pyls-spyder
    - python-qdarkstyle
    - python-qstylizer
    - python-qtawesome
    - python-qtconsole
    - python-qtwebengine
    - python-rope
    - python-spyder-kernels
    - python-textdistance
    - python-three-merge
    - python-watchdog
    - pyxdg
    - scipy
    - sympy
setup      : |
    sed "s|'pyqt5<5.13'|'pyqt5'|" -i setup.py
    sed "s|'pyqtwebengine<5.13'|'pyqtwebengine'|" -i setup.py
build      : |
    %python3_setup
install    : |
    %python3_install

    # Move icon to pixmaps
    install -dm00644 $installdir/usr/share/pixmaps
    mv $installdir/usr/share/icons/spyder.png $installdir/usr/share/pixmaps/spyder.png

    # Symlinking spyder3 to reduce breakages
    ln -sv /usr/bin/spyder $installdir/usr/bin/spyder3

    # Remove empty directory
    rm -rf $installdir/usr/share/icons
