name       : spyder3
version    : 5.3.3
release    : 27
source     :
    - https://github.com/spyder-ide/spyder/archive/refs/tags/v5.3.3.tar.gz : 1e59bbddb1846e777e6938d6f600c57466bf8df8c30fdccf17838838b8666ec7
homepage   : https://www.spyder-ide.org/
license    :
    - BSD-3-Clause
    - CC-BY-2.5
    - CC-BY-3.0
    - CC-BY-SA-4.0
    - EPL-1.0
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
    - MIT
    - Python-2.0
    - Zlib
component  : programming.ide
summary    : The Scientific Python Development Environment
description: |
    Spyder is a powerful scientific environment written in Python, for Python, and designed by and for scientists, engineers and data analysts. It offers a unique combination of the advanced editing, analysis, debugging, and profiling functionality of a comprehensive development tool with the data exploration, interactive execution, deep inspection, and beautiful visualization capabilities of a scientific package.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - cython
    - matplotlib
    - python-atomicwrites
    - python-chardet
    - python-cookiecutter
    - python-intervaltree
    - python-jellyfish
    - python-keyring
    - python-lsp-black
    - python-nbconvert
    - python-numpydoc
    - python-opengl
    - python-pandas
    - python-psutil
    - python-pyls-spyder
    - python-qdarkstyle
    - python-qstylizer
    - python-qtawesome
    - python-qtconsole
    - python-qtwebengine
    - python-rtree
    - python-spyder-kernels
    - python-textdistance
    - python-three-merge
    - python-watchdog
    - pyxdg
    - scipy
    - sympy
build      : |
    %python3_setup
install    : |
    %python3_install

    # Move icon to pixmaps
    install -dm00644 $installdir/usr/share/pixmaps
    mv $installdir/usr/share/icons/spyder.png $installdir/usr/share/pixmaps/spyder.png

    # Symlinking spyder3 to reduce breakages
    ln -sv /usr/bin/spyder $installdir/usr/bin/spyder3

    # Remove empty directory
    rm -rf $installdir/usr/share/icons
